-- NexArtPro — Full Schema (Part 1: Core Tables)
-- Run this in Supabase SQL Editor

-- ═══════════════════════════════════════
-- CLIENTS
-- ═══════════════════════════════════════
CREATE TABLE IF NOT EXISTS clients (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  full_name TEXT NOT NULL,
  email TEXT,
  phone TEXT,
  address TEXT,
  city TEXT,
  state TEXT,
  zip TEXT,
  notes TEXT,
  property_value NUMERIC,
  beds INTEGER,
  baths NUMERIC,
  sqft NUMERIC,
  preferred_language TEXT DEFAULT 'en',
  deleted_at TIMESTAMPTZ,
  deleted_by TEXT,
  delete_reason TEXT,
  restored_at TIMESTAMPTZ,
  restored_by TEXT,
  created_date TIMESTAMPTZ DEFAULT now(),
  updated_date TIMESTAMPTZ DEFAULT now()
);

-- ═══════════════════════════════════════
-- CUSTOMERS
-- ═══════════════════════════════════════
CREATE TABLE IF NOT EXISTS customers (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  first_name TEXT NOT NULL,
  last_name TEXT NOT NULL,
  display_name TEXT,
  email TEXT,
  phone TEXT,
  customer_type TEXT DEFAULT 'residential',
  company_name TEXT,
  service_address TEXT,
  city TEXT,
  state TEXT,
  zip TEXT,
  notes TEXT,
  internal_notes TEXT,
  preferred_language TEXT DEFAULT 'en',
  deleted_at TIMESTAMPTZ,
  deleted_by TEXT,
  delete_reason TEXT,
  restored_at TIMESTAMPTZ,
  restored_by TEXT,
  company_id TEXT DEFAULT 'rc-art',
  created_date TIMESTAMPTZ DEFAULT now(),
  updated_date TIMESTAMPTZ DEFAULT now()
);

-- ═══════════════════════════════════════
-- LEADS
-- ═══════════════════════════════════════
CREATE TABLE IF NOT EXISTS leads (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name TEXT NOT NULL,
  phone TEXT,
  email TEXT,
  address TEXT,
  service TEXT,
  details TEXT,
  status TEXT DEFAULT 'new',
  source TEXT DEFAULT 'website',
  deleted_at TIMESTAMPTZ,
  deleted_by TEXT,
  delete_reason TEXT,
  restored_at TIMESTAMPTZ,
  restored_by TEXT,
  created_date TIMESTAMPTZ DEFAULT now(),
  updated_date TIMESTAMPTZ DEFAULT now()
);

-- ═══════════════════════════════════════
-- SERVICES
-- ═══════════════════════════════════════
CREATE TABLE IF NOT EXISTS services (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name TEXT NOT NULL,
  type TEXT DEFAULT 'service',
  category TEXT,
  unit TEXT,
  description TEXT,
  unit_price NUMERIC DEFAULT 0,
  unit_cost NUMERIC DEFAULT 0,
  book_price NUMERIC DEFAULT 0,
  is_active BOOLEAN DEFAULT true,
  created_date TIMESTAMPTZ DEFAULT now(),
  updated_date TIMESTAMPTZ DEFAULT now()
);

-- ═══════════════════════════════════════
-- MATERIALS
-- ═══════════════════════════════════════
CREATE TABLE IF NOT EXISTS materials (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  material_name TEXT NOT NULL,
  category TEXT,
  unit TEXT,
  unit_cost NUMERIC DEFAULT 0,
  supplier TEXT,
  sku_or_ref TEXT,
  notes TEXT,
  is_active BOOLEAN DEFAULT true,
  created_date TIMESTAMPTZ DEFAULT now(),
  updated_date TIMESTAMPTZ DEFAULT now()
);

-- ═══════════════════════════════════════
-- WORKERS
-- ═══════════════════════════════════════
CREATE TABLE IF NOT EXISTS workers (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  full_name TEXT NOT NULL,
  first_name TEXT,
  last_name TEXT,
  worker_type TEXT DEFAULT 'employee',
  trade TEXT DEFAULT 'general',
  role TEXT DEFAULT 'technician',
  active BOOLEAN DEFAULT true,
  phone TEXT,
  alternate_phone TEXT,
  email TEXT,
  company_name TEXT,
  address TEXT,
  city TEXT,
  state TEXT,
  zip TEXT,
  emergency_contact TEXT,
  emergency_phone TEXT,
  hire_date DATE,
  start_date DATE,
  end_date DATE,
  license_number TEXT,
  license_expiry DATE,
  insurance_expiry DATE,
  hourly_rate NUMERIC,
  avatar_url TEXT,
  notes TEXT,
  internal_notes TEXT,
  created_date TIMESTAMPTZ DEFAULT now(),
  updated_date TIMESTAMPTZ DEFAULT now()
);

-- ═══════════════════════════════════════
-- ESTIMATES
-- ═══════════════════════════════════════
CREATE TABLE IF NOT EXISTS estimates (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  estimate_number INTEGER,
  document_type TEXT DEFAULT 'ESTIMATE',
  document_language TEXT DEFAULT 'en',
  version_number INTEGER DEFAULT 1,
  parent_estimate_id TEXT,
  job_number TEXT,
  plan_reference TEXT,
  client_id TEXT,
  client_name TEXT,
  client_email TEXT,
  client_phone TEXT,
  client_address TEXT,
  title TEXT,
  description TEXT,
  project_start_date TEXT,
  project_end_date TEXT,
  expiration_date TEXT,
  assigned_to TEXT,
  appointment_id TEXT,
  status TEXT DEFAULT 'draft',
  sales_stage TEXT,
  groups JSONB DEFAULT '[]',
  materials JSONB DEFAULT '[]',
  other_costs JSONB DEFAULT '[]',
  line_items JSONB DEFAULT '[]',
  attachments JSONB DEFAULT '[]',
  services_subtotal NUMERIC DEFAULT 0,
  materials_subtotal NUMERIC DEFAULT 0,
  subtotal NUMERIC DEFAULT 0,
  tax_rate NUMERIC DEFAULT 0,
  tax_amount NUMERIC DEFAULT 0,
  discount_type TEXT DEFAULT 'percent',
  discount_value NUMERIC DEFAULT 0,
  discount_amount NUMERIC DEFAULT 0,
  total NUMERIC DEFAULT 0,
  deposit_percent NUMERIC DEFAULT 0,
  deposit_amount NUMERIC DEFAULT 0,
  service_cost NUMERIC DEFAULT 0,
  materials_cost NUMERIC DEFAULT 0,
  other_costs_total NUMERIC DEFAULT 0,
  total_cost NUMERIC DEFAULT 0,
  total_book_value NUMERIC DEFAULT 0,
  total_variance NUMERIC DEFAULT 0,
  margin_percentage NUMERIC DEFAULT 0,
  gross_margin NUMERIC DEFAULT 0,
  gross_margin_pct NUMERIC DEFAULT 0,
  net_profit NUMERIC DEFAULT 0,
  net_profit_pct NUMERIC DEFAULT 0,
  notes TEXT,
  internal_notes TEXT,
  exclusions TEXT,
  payment_terms TEXT,
  warranty_terms TEXT,
  legal_terms TEXT,
  scope_summary TEXT,
  assumptions TEXT,
  change_request_policy TEXT,
  included_scope_bullets TEXT,
  uncertainty_note TEXT,
  contingency_type TEXT DEFAULT 'none',
  contingency_value NUMERIC DEFAULT 0,
  contingency_amount NUMERIC DEFAULT 0,
  show_contingency_to_client BOOLEAN DEFAULT false,
  document_config JSONB,
  public_share_token TEXT,
  public_share_token_created_at TIMESTAMPTZ,
  sent_at TIMESTAMPTZ,
  viewed_at TIMESTAMPTZ,
  approved_at TIMESTAMPTZ,
  signed_at TIMESTAMPTZ,
  accepted_by TEXT,
  signature_name TEXT,
  signature_image TEXT,
  signature_method TEXT,
  company_signature_name TEXT,
  company_signature_email TEXT,
  company_signature_role TEXT,
  company_signed_at TIMESTAMPTZ,
  signing_package_id TEXT,
  signature_status TEXT DEFAULT 'not_sent',
  terms_accepted BOOLEAN DEFAULT false,
  legal_audit JSONB,
  signature_certificate JSONB,
  document_hash TEXT,
  document_hash_algorithm TEXT DEFAULT 'SHA-256',
  certificate_generated_at TIMESTAMPTZ,
  signed_pdf_hash TEXT,
  signed_pdf_hash_algorithm TEXT DEFAULT 'SHA-256',
  signature_provider TEXT DEFAULT 'internal',
  external_signature_request_id TEXT,
  external_signature_status TEXT,
  external_signature_url TEXT,
  external_signature_provider_payload JSONB,
  external_signature_completed_at TIMESTAMPTZ,
  external_signature_certificate_url TEXT,
  external_signature_signed_pdf_url TEXT,
  locked_after_signature BOOLEAN DEFAULT false,
  final_signed_at TIMESTAMPTZ,
  final_signed_pdf_name TEXT,
  legal_package_locked BOOLEAN DEFAULT false,
  declined_at TIMESTAMPTZ,
  declined_reason TEXT,
  converted_to_work_order_at TIMESTAMPTZ,
  converted_work_order_id TEXT,
  converted_invoice_id TEXT,
  final_signed_pdf_url TEXT,
  updated_by TEXT,
  deleted_at TIMESTAMPTZ,
  deleted_by TEXT,
  delete_reason TEXT,
  restored_at TIMESTAMPTZ,
  restored_by TEXT,
  created_date TIMESTAMPTZ DEFAULT now(),
  updated_date TIMESTAMPTZ DEFAULT now()
);

-- ═══════════════════════════════════════
-- WORK ORDERS
-- ═══════════════════════════════════════
CREATE TABLE IF NOT EXISTS work_orders (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  work_order_number INTEGER,
  estimate_id TEXT,
  estimate_version INTEGER DEFAULT 1,
  source_estimate_id TEXT,
  source_estimate_number INTEGER,
  source_estimate_version INTEGER DEFAULT 1,
  source_document_type TEXT,
  source_estimate_status TEXT,
  source_estimate_total NUMERIC DEFAULT 0,
  source_estimate_signed_at TIMESTAMPTZ,
  source_estimate_signed_by TEXT,
  source_estimate_final_pdf_url TEXT,
  source_estimate_snapshot JSONB,
  source_proposal_id TEXT,
  source_proposal_number INTEGER,
  source_close_outcome TEXT,
  source_selected_pricing_option_id TEXT,
  source_selected_pricing_option_title TEXT,
  client_id TEXT,
  client_name TEXT,
  client_email TEXT,
  client_address TEXT,
  client_phone TEXT,
  title TEXT,
  description TEXT,
  status TEXT DEFAULT 'draft',
  assigned_user_id TEXT,
  assigned_worker_id TEXT,
  assigned_to_id TEXT,
  assigned_user_name TEXT,
  assigned_worker_name TEXT,
  assigned_to TEXT,
  assigned_user_email TEXT,
  assigned_worker_email TEXT,
  assigned_email TEXT,
  assigned_worker_phone TEXT,
  assigned_by TEXT,
  assigned_at TEXT,
  assignment_source TEXT,
  assigned_crew JSONB DEFAULT '[]',
  assigned_crew_ids JSONB DEFAULT '[]',
  assigned_crew_names JSONB DEFAULT '[]',
  crew_size INTEGER DEFAULT 0,
  previous_worker_id TEXT,
  previous_worker_name TEXT,
  reassigned_at TEXT,
  reassigned_by TEXT,
  performed_by_worker_id TEXT,
  performed_by_worker_name TEXT,
  performed_by_corrected_at TEXT,
  performed_by_corrected_by TEXT,
  completed_by_user TEXT,
  completed_by_user_id TEXT,
  scheduled_date DATE,
  scheduled_time TEXT,
  arrival_time TEXT,
  departure_time TEXT,
  groups JSONB DEFAULT '[]',
  line_items JSONB DEFAULT '[]',
  materials JSONB DEFAULT '[]',
  other_costs JSONB DEFAULT '[]',
  subtotal NUMERIC,
  total NUMERIC,
  materials_subtotal NUMERIC DEFAULT 0,
  materials_cost NUMERIC DEFAULT 0,
  other_costs_total NUMERIC DEFAULT 0,
  total_cost NUMERIC DEFAULT 0,
  gross_margin NUMERIC DEFAULT 0,
  gross_margin_pct NUMERIC DEFAULT 0,
  payment_terms TEXT,
  warranty_terms TEXT,
  exclusions TEXT,
  scope_summary TEXT,
  assumptions TEXT,
  notes TEXT,
  internal_notes TEXT,
  admin_correction_notes TEXT,
  completed_at TEXT,
  started_at TEXT,
  work_summary TEXT,
  issues_found TEXT,
  field_notes JSONB DEFAULT '[]',
  execution_checklist JSONB DEFAULT '[]',
  tasks JSONB DEFAULT '[]',
  task_statuses JSONB,
  company_id TEXT DEFAULT 'rc-art',
  created_date TIMESTAMPTZ DEFAULT now(),
  updated_date TIMESTAMPTZ DEFAULT now()
);

-- ═══════════════════════════════════════
-- INVOICES
-- ═══════════════════════════════════════
CREATE TABLE IF NOT EXISTS invoices (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  invoice_number INTEGER,
  work_order_id TEXT,
  estimate_id TEXT,
  estimate_version INTEGER,
  source_proposal_id TEXT,
  source_proposal_number INTEGER,
  source_close_outcome TEXT,
  source_selected_pricing_option_id TEXT,
  source_selected_pricing_option_title TEXT,
  client_id TEXT,
  client_name TEXT,
  client_email TEXT,
  client_address TEXT,
  client_phone TEXT,
  title TEXT,
  status TEXT DEFAULT 'draft',
  due_date DATE,
  groups JSONB DEFAULT '[]',
  line_items JSONB DEFAULT '[]',
  subtotal NUMERIC,
  discount_type TEXT DEFAULT 'percent',
  discount_value NUMERIC DEFAULT 0,
  discount_amount NUMERIC DEFAULT 0,
  tax_rate NUMERIC DEFAULT 0,
  tax_amount NUMERIC,
  total NUMERIC,
  payments JSONB DEFAULT '[]',
  amount_paid NUMERIC DEFAULT 0,
  balance_due NUMERIC DEFAULT 0,
  payment_status TEXT DEFAULT 'unpaid',
  notes TEXT,
  internal_notes TEXT,
  payment_terms TEXT,
  client_response_status TEXT DEFAULT 'no_response',
  client_response_note TEXT,
  client_response_at TIMESTAMPTZ,
  promised_payment_date DATE,
  promised_payment_note TEXT,
  billing_issue_status TEXT,
  billing_issue_note TEXT,
  billing_issue_opened_at TIMESTAMPTZ,
  billing_issue_resolved_at TIMESTAMPTZ,
  billing_issue_owner TEXT,
  billing_issue_resolution_note TEXT,
  sla_last_reviewed_at TIMESTAMPTZ,
  sla_last_reviewed_by TEXT,
  sla_resolution_note TEXT,
  sla_resolved_types JSONB DEFAULT '[]',
  sla_resolved_at TIMESTAMPTZ,
  collection_timeline JSONB DEFAULT '[]',
  last_contacted_at TIMESTAMPTZ,
  sent_at TEXT,
  paid_at TEXT,
  company_id TEXT DEFAULT 'rc-art',
  created_date TIMESTAMPTZ DEFAULT now(),
  updated_date TIMESTAMPTZ DEFAULT now()
);

-- ═══════════════════════════════════════
-- PROPOSALS
-- ═══════════════════════════════════════
CREATE TABLE IF NOT EXISTS proposals (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  proposal_number INTEGER,
  source_estimate_id TEXT,
  creation_mode TEXT DEFAULT 'new_proposal',
  client_id TEXT,
  client_name TEXT,
  client_email TEXT,
  client_phone TEXT,
  client_address TEXT,
  title TEXT,
  status TEXT DEFAULT 'draft',
  document_language TEXT DEFAULT 'en',
  items JSONB DEFAULT '[]',
  subtotal NUMERIC DEFAULT 0,
  tax_rate NUMERIC DEFAULT 0,
  tax_amount NUMERIC DEFAULT 0,
  discount_value NUMERIC DEFAULT 0,
  total_amount NUMERIC DEFAULT 0,
  total_cost NUMERIC DEFAULT 0,
  gross_margin NUMERIC DEFAULT 0,
  gross_margin_pct NUMERIC DEFAULT 0,
  payment_terms TEXT,
  legal_terms TEXT,
  notes TEXT,
  proposal_details JSONB,
  internal_notes TEXT,
  expiration_date DATE,
  template_name TEXT DEFAULT 'professional',
  sent_at TEXT,
  viewed_at TEXT,
  last_viewed_at TEXT,
  view_count INTEGER DEFAULT 0,
  approved_at TEXT,
  accepted_at TEXT,
  accepted_ip TEXT,
  accepted_user_agent TEXT,
  accepted_by_name TEXT,
  signature_on_file BOOLEAN DEFAULT false,
  signature_image_base64 TEXT,
  acceptance_proof JSONB,
  rejected_at TEXT,
  rejected_reason TEXT,
  invoice_id TEXT,
  invoice_number TEXT,
  work_order_id TEXT,
  work_order_number INTEGER,
  adjustment_estimate_id TEXT,
  adjustment_estimate_number INTEGER,
  adjustment_reason TEXT,
  last_follow_up_at TEXT,
  next_follow_up_at TEXT,
  follow_up_note TEXT,
  follow_up_count INTEGER DEFAULT 0,
  closed_at TEXT,
  close_outcome TEXT,
  lost_reason TEXT,
  close_note TEXT,
  selected_pricing_option_id TEXT,
  selected_pricing_option_title TEXT,
  company_id TEXT DEFAULT 'rc-art',
  created_date TIMESTAMPTZ DEFAULT now(),
  updated_date TIMESTAMPTZ DEFAULT now()
);

-- ═══════════════════════════════════════
-- APPOINTMENTS
-- ═══════════════════════════════════════
CREATE TABLE IF NOT EXISTS appointments (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  customer_id TEXT,
  customer_display_name TEXT,
  customer_phone TEXT,
  customer_email TEXT,
  title TEXT,
  service_type TEXT,
  description TEXT,
  appointment_date DATE,
  start_time TEXT,
  end_time TEXT,
  arrival_window TEXT,
  service_address TEXT,
  status TEXT DEFAULT 'new',
  assigned_worker_id TEXT,
  assigned_worker_name TEXT,
  notes TEXT,
  internal_notes TEXT,
  notify_customer BOOLEAN DEFAULT true,
  confirmation_sent_at TEXT,
  reminder_sent_at TEXT,
  omw_started_at TEXT,
  arrived_at TEXT,
  completed_at TEXT,
  estimate_id TEXT,
  created_date TIMESTAMPTZ DEFAULT now(),
  updated_date TIMESTAMPTZ DEFAULT now()
);

-- ═══════════════════════════════════════
-- PAYMENTS
-- ═══════════════════════════════════════
CREATE TABLE IF NOT EXISTS payments (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  invoice_id TEXT,
  invoice_number INTEGER,
  client_name TEXT,
  amount NUMERIC DEFAULT 0,
  payment_method TEXT DEFAULT 'cash',
  payment_date DATE,
  notes TEXT,
  created_date TIMESTAMPTZ DEFAULT now(),
  updated_date TIMESTAMPTZ DEFAULT now()
);
