-- NexArtPro — Database Schema Fix: Add Missing Columns
-- Generated by audit comparing base44/entities/*.jsonc vs Supabase tables
-- Run this in Supabase SQL Editor

-- ═══ AuditLog → audit_logs (6 missing) ═══
ALTER TABLE audit_logs ADD COLUMN IF NOT EXISTS action TEXT;
ALTER TABLE audit_logs ADD COLUMN IF NOT EXISTS company_id TEXT DEFAULT 'rc-art';
ALTER TABLE audit_logs ADD COLUMN IF NOT EXISTS entity_id TEXT;
ALTER TABLE audit_logs ADD COLUMN IF NOT EXISTS performed_at TIMESTAMPTZ;
ALTER TABLE audit_logs ADD COLUMN IF NOT EXISTS performed_by TEXT;
ALTER TABLE audit_logs ADD COLUMN IF NOT EXISTS reason TEXT;

-- ═══ AuthSecurityLog → auth_security_logs (6 missing) ═══
ALTER TABLE auth_security_logs ADD COLUMN IF NOT EXISTS metadata_json JSONB;
ALTER TABLE auth_security_logs ADD COLUMN IF NOT EXISTS origin_path TEXT;
ALTER TABLE auth_security_logs ADD COLUMN IF NOT EXISTS reason TEXT;
ALTER TABLE auth_security_logs ADD COLUMN IF NOT EXISTS success BOOLEAN DEFAULT false;
ALTER TABLE auth_security_logs ADD COLUMN IF NOT EXISTS user_id TEXT;
ALTER TABLE auth_security_logs ADD COLUMN IF NOT EXISTS user_identifier TEXT;

-- ═══ BankAccount → bank_accounts (5 missing) ═══
ALTER TABLE bank_accounts ADD COLUMN IF NOT EXISTS account_type TEXT DEFAULT 'checking';
ALTER TABLE bank_accounts ADD COLUMN IF NOT EXISTS bank_name TEXT;
ALTER TABLE bank_accounts ADD COLUMN IF NOT EXISTS currency TEXT DEFAULT 'USD';
ALTER TABLE bank_accounts ADD COLUMN IF NOT EXISTS current_balance NUMERIC DEFAULT 0;
ALTER TABLE bank_accounts ADD COLUMN IF NOT EXISTS is_active BOOLEAN DEFAULT false;

-- ═══ BankTransaction → bank_transactions (12 missing) ═══
ALTER TABLE bank_transactions ADD COLUMN IF NOT EXISTS bank_account_name TEXT;
ALTER TABLE bank_transactions ADD COLUMN IF NOT EXISTS category TEXT DEFAULT 'miscellaneous';
ALTER TABLE bank_transactions ADD COLUMN IF NOT EXISTS date DATE;
ALTER TABLE bank_transactions ADD COLUMN IF NOT EXISTS description TEXT;
ALTER TABLE bank_transactions ADD COLUMN IF NOT EXISTS is_reviewed BOOLEAN DEFAULT false;
ALTER TABLE bank_transactions ADD COLUMN IF NOT EXISTS notes TEXT;
ALTER TABLE bank_transactions ADD COLUMN IF NOT EXISTS related_customer_id TEXT;
ALTER TABLE bank_transactions ADD COLUMN IF NOT EXISTS related_customer_name TEXT;
ALTER TABLE bank_transactions ADD COLUMN IF NOT EXISTS related_expense_id TEXT;
ALTER TABLE bank_transactions ADD COLUMN IF NOT EXISTS related_work_order_id TEXT;
ALTER TABLE bank_transactions ADD COLUMN IF NOT EXISTS related_work_order_number NUMERIC;
ALTER TABLE bank_transactions ADD COLUMN IF NOT EXISTS type TEXT DEFAULT 'expense';

-- ═══ CommEvent → comm_events (9 missing) ═══
ALTER TABLE comm_events ADD COLUMN IF NOT EXISTS appointment_id TEXT;
ALTER TABLE comm_events ADD COLUMN IF NOT EXISTS channel TEXT DEFAULT 'email';
ALTER TABLE comm_events ADD COLUMN IF NOT EXISTS client_email TEXT;
ALTER TABLE comm_events ADD COLUMN IF NOT EXISTS client_id TEXT;
ALTER TABLE comm_events ADD COLUMN IF NOT EXISTS client_name TEXT;
ALTER TABLE comm_events ADD COLUMN IF NOT EXISTS estimate_id TEXT;
ALTER TABLE comm_events ADD COLUMN IF NOT EXISTS event_type TEXT;
ALTER TABLE comm_events ADD COLUMN IF NOT EXISTS preview TEXT;
ALTER TABLE comm_events ADD COLUMN IF NOT EXISTS subject TEXT;

-- ═══ DocumentLog → document_logs (10 missing) ═══
ALTER TABLE document_logs ADD COLUMN IF NOT EXISTS action TEXT DEFAULT 'sent_email';
ALTER TABLE document_logs ADD COLUMN IF NOT EXISTS client_email TEXT;
ALTER TABLE document_logs ADD COLUMN IF NOT EXISTS client_name TEXT;
ALTER TABLE document_logs ADD COLUMN IF NOT EXISTS estimate_id TEXT;
ALTER TABLE document_logs ADD COLUMN IF NOT EXISTS estimate_number NUMERIC;
ALTER TABLE document_logs ADD COLUMN IF NOT EXISTS recipient_email TEXT;
ALTER TABLE document_logs ADD COLUMN IF NOT EXISTS secure_link TEXT;
ALTER TABLE document_logs ADD COLUMN IF NOT EXISTS status_at_send TEXT;
ALTER TABLE document_logs ADD COLUMN IF NOT EXISTS subject TEXT;
ALTER TABLE document_logs ADD COLUMN IF NOT EXISTS total_amount NUMERIC;

-- ═══ EstimateSnapshot → estimate_snapshots (16 missing) ═══
ALTER TABLE estimate_snapshots ADD COLUMN IF NOT EXISTS client_attachments JSONB;
ALTER TABLE estimate_snapshots ADD COLUMN IF NOT EXISTS client_email TEXT;
ALTER TABLE estimate_snapshots ADD COLUMN IF NOT EXISTS client_id TEXT;
ALTER TABLE estimate_snapshots ADD COLUMN IF NOT EXISTS document_config JSONB;
ALTER TABLE estimate_snapshots ADD COLUMN IF NOT EXISTS document_language TEXT DEFAULT 'en';
ALTER TABLE estimate_snapshots ADD COLUMN IF NOT EXISTS document_type TEXT DEFAULT 'ESTIMATE';
ALTER TABLE estimate_snapshots ADD COLUMN IF NOT EXISTS estimate_data JSONB;
ALTER TABLE estimate_snapshots ADD COLUMN IF NOT EXISTS estimate_number NUMERIC;
ALTER TABLE estimate_snapshots ADD COLUMN IF NOT EXISTS pdf_file_name TEXT;
ALTER TABLE estimate_snapshots ADD COLUMN IF NOT EXISTS pdf_file_url TEXT;
ALTER TABLE estimate_snapshots ADD COLUMN IF NOT EXISTS pdf_mime_type TEXT DEFAULT 'application/pdf';
ALTER TABLE estimate_snapshots ADD COLUMN IF NOT EXISTS sent_at TIMESTAMPTZ;
ALTER TABLE estimate_snapshots ADD COLUMN IF NOT EXISTS sent_by TEXT;
ALTER TABLE estimate_snapshots ADD COLUMN IF NOT EXISTS title TEXT;
ALTER TABLE estimate_snapshots ADD COLUMN IF NOT EXISTS total NUMERIC;
ALTER TABLE estimate_snapshots ADD COLUMN IF NOT EXISTS version NUMERIC;

-- ═══ EstimateTransmission → estimate_transmissions (13 missing) ═══
ALTER TABLE estimate_transmissions ADD COLUMN IF NOT EXISTS bounced_at TIMESTAMPTZ;
ALTER TABLE estimate_transmissions ADD COLUMN IF NOT EXISTS client_name TEXT;
ALTER TABLE estimate_transmissions ADD COLUMN IF NOT EXISTS company_id TEXT DEFAULT 'rc-art';
ALTER TABLE estimate_transmissions ADD COLUMN IF NOT EXISTS delivered_at TIMESTAMPTZ;
ALTER TABLE estimate_transmissions ADD COLUMN IF NOT EXISTS document_type TEXT;
ALTER TABLE estimate_transmissions ADD COLUMN IF NOT EXISTS error_message TEXT;
ALTER TABLE estimate_transmissions ADD COLUMN IF NOT EXISTS estimate_number NUMERIC;
ALTER TABLE estimate_transmissions ADD COLUMN IF NOT EXISTS failed_at TIMESTAMPTZ;
ALTER TABLE estimate_transmissions ADD COLUMN IF NOT EXISTS opened_at TIMESTAMPTZ;
ALTER TABLE estimate_transmissions ADD COLUMN IF NOT EXISTS provider TEXT DEFAULT 'resend';
ALTER TABLE estimate_transmissions ADD COLUMN IF NOT EXISTS provider_message_id TEXT;
ALTER TABLE estimate_transmissions ADD COLUMN IF NOT EXISTS snapshot_id TEXT;
ALTER TABLE estimate_transmissions ADD COLUMN IF NOT EXISTS status TEXT DEFAULT 'sent';

-- ═══ EstimateVersionHistory → estimate_version_histories (9 missing) ═══
ALTER TABLE estimate_version_histories ADD COLUMN IF NOT EXISTS archived_by TEXT;
ALTER TABLE estimate_version_histories ADD COLUMN IF NOT EXISTS archived_reason TEXT DEFAULT 'changes_requested';
ALTER TABLE estimate_version_histories ADD COLUMN IF NOT EXISTS changes_note TEXT;
ALTER TABLE estimate_version_histories ADD COLUMN IF NOT EXISTS client_name TEXT;
ALTER TABLE estimate_version_histories ADD COLUMN IF NOT EXISTS estimate_number NUMERIC;
ALTER TABLE estimate_version_histories ADD COLUMN IF NOT EXISTS snapshot JSONB;
ALTER TABLE estimate_version_histories ADD COLUMN IF NOT EXISTS status_at_archive TEXT;
ALTER TABLE estimate_version_histories ADD COLUMN IF NOT EXISTS total_at_archive NUMERIC;
ALTER TABLE estimate_version_histories ADD COLUMN IF NOT EXISTS version NUMERIC;

-- ═══ JobAssignment → job_assignments (10 missing) ═══
ALTER TABLE job_assignments ADD COLUMN IF NOT EXISTS action TEXT DEFAULT 'assigned';
ALTER TABLE job_assignments ADD COLUMN IF NOT EXISTS client_name TEXT;
ALTER TABLE job_assignments ADD COLUMN IF NOT EXISTS note TEXT;
ALTER TABLE job_assignments ADD COLUMN IF NOT EXISTS previous_worker_name TEXT;
ALTER TABLE job_assignments ADD COLUMN IF NOT EXISTS scheduled_date DATE;
ALTER TABLE job_assignments ADD COLUMN IF NOT EXISTS title TEXT;
ALTER TABLE job_assignments ADD COLUMN IF NOT EXISTS worker_id TEXT;
ALTER TABLE job_assignments ADD COLUMN IF NOT EXISTS worker_name TEXT;
ALTER TABLE job_assignments ADD COLUMN IF NOT EXISTS worker_phone TEXT;
ALTER TABLE job_assignments ADD COLUMN IF NOT EXISTS work_order_number NUMERIC;

-- ═══ PriceBookEntry → price_book_entries (9 missing) ═══
ALTER TABLE price_book_entries ADD COLUMN IF NOT EXISTS category TEXT;
ALTER TABLE price_book_entries ADD COLUMN IF NOT EXISTS display_name TEXT;
ALTER TABLE price_book_entries ADD COLUMN IF NOT EXISTS is_active BOOLEAN DEFAULT false;
ALTER TABLE price_book_entries ADD COLUMN IF NOT EXISTS markup NUMERIC;
ALTER TABLE price_book_entries ADD COLUMN IF NOT EXISTS needs_review BOOLEAN DEFAULT false;
ALTER TABLE price_book_entries ADD COLUMN IF NOT EXISTS source TEXT DEFAULT 'manual';
ALTER TABLE price_book_entries ADD COLUMN IF NOT EXISTS type TEXT DEFAULT 'service';
ALTER TABLE price_book_entries ADD COLUMN IF NOT EXISTS unit TEXT;
ALTER TABLE price_book_entries ADD COLUMN IF NOT EXISTS unit_cost NUMERIC DEFAULT 0;

-- ═══ PricingAuditEvent → pricing_audit_events (6 missing) ═══
ALTER TABLE pricing_audit_events ADD COLUMN IF NOT EXISTS document_id TEXT;
ALTER TABLE pricing_audit_events ADD COLUMN IF NOT EXISTS document_kind TEXT;
ALTER TABLE pricing_audit_events ADD COLUMN IF NOT EXISTS event_type TEXT;
ALTER TABLE pricing_audit_events ADD COLUMN IF NOT EXISTS metadata JSONB;
ALTER TABLE pricing_audit_events ADD COLUMN IF NOT EXISTS user_email TEXT;
ALTER TABLE pricing_audit_events ADD COLUMN IF NOT EXISTS user_role TEXT;

-- ═══ ProjectPhoto → project_photos (7 missing) ═══
ALTER TABLE project_photos ADD COLUMN IF NOT EXISTS appointment_id TEXT;
ALTER TABLE project_photos ADD COLUMN IF NOT EXISTS customer_id TEXT;
ALTER TABLE project_photos ADD COLUMN IF NOT EXISTS customer_name TEXT;
ALTER TABLE project_photos ADD COLUMN IF NOT EXISTS phase TEXT DEFAULT 'before';
ALTER TABLE project_photos ADD COLUMN IF NOT EXISTS photo_url TEXT;
ALTER TABLE project_photos ADD COLUMN IF NOT EXISTS taken_by TEXT;
ALTER TABLE project_photos ADD COLUMN IF NOT EXISTS work_order_number NUMERIC;

-- ═══ PublicDocumentAccess → public_document_access (9 missing) ═══
ALTER TABLE public_document_access ADD COLUMN IF NOT EXISTS client_email TEXT;
ALTER TABLE public_document_access ADD COLUMN IF NOT EXISTS company_id TEXT DEFAULT 'rc-art';
ALTER TABLE public_document_access ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ;
ALTER TABLE public_document_access ADD COLUMN IF NOT EXISTS document_id TEXT;
ALTER TABLE public_document_access ADD COLUMN IF NOT EXISTS document_number TEXT;
ALTER TABLE public_document_access ADD COLUMN IF NOT EXISTS last_used_at TIMESTAMPTZ;
ALTER TABLE public_document_access ADD COLUMN IF NOT EXISTS metadata JSONB;
ALTER TABLE public_document_access ADD COLUMN IF NOT EXISTS status TEXT DEFAULT 'active';
ALTER TABLE public_document_access ADD COLUMN IF NOT EXISTS token TEXT;

-- ═══ RecoveryVault → recovery_vault (16 missing) ═══
ALTER TABLE recovery_vault ADD COLUMN IF NOT EXISTS company_id TEXT DEFAULT 'rc-art';
ALTER TABLE recovery_vault ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMPTZ;
ALTER TABLE recovery_vault ADD COLUMN IF NOT EXISTS delete_reason TEXT;
ALTER TABLE recovery_vault ADD COLUMN IF NOT EXISTS entity_id TEXT;
ALTER TABLE recovery_vault ADD COLUMN IF NOT EXISTS is_purged BOOLEAN DEFAULT false;
ALTER TABLE recovery_vault ADD COLUMN IF NOT EXISTS is_restored BOOLEAN DEFAULT false;
ALTER TABLE recovery_vault ADD COLUMN IF NOT EXISTS module TEXT;
ALTER TABLE recovery_vault ADD COLUMN IF NOT EXISTS origin_path TEXT;
ALTER TABLE recovery_vault ADD COLUMN IF NOT EXISTS purged_at TIMESTAMPTZ;
ALTER TABLE recovery_vault ADD COLUMN IF NOT EXISTS purged_by TEXT;
ALTER TABLE recovery_vault ADD COLUMN IF NOT EXISTS record_label TEXT;
ALTER TABLE recovery_vault ADD COLUMN IF NOT EXISTS reference_number TEXT;
ALTER TABLE recovery_vault ADD COLUMN IF NOT EXISTS restored_at TIMESTAMPTZ;
ALTER TABLE recovery_vault ADD COLUMN IF NOT EXISTS restored_by TEXT;
ALTER TABLE recovery_vault ADD COLUMN IF NOT EXISTS search_text TEXT;
ALTER TABLE recovery_vault ADD COLUMN IF NOT EXISTS snapshot_json JSONB;

-- ═══ SigningCertificate → signing_certificates (13 missing) ═══
ALTER TABLE signing_certificates ADD COLUMN IF NOT EXISTS audit_trail JSONB;
ALTER TABLE signing_certificates ADD COLUMN IF NOT EXISTS certificate_number TEXT;
ALTER TABLE signing_certificates ADD COLUMN IF NOT EXISTS company_id TEXT DEFAULT 'rc-art';
ALTER TABLE signing_certificates ADD COLUMN IF NOT EXISTS document_id TEXT;
ALTER TABLE signing_certificates ADD COLUMN IF NOT EXISTS document_type TEXT;
ALTER TABLE signing_certificates ADD COLUMN IF NOT EXISTS final_pdf_hash TEXT;
ALTER TABLE signing_certificates ADD COLUMN IF NOT EXISTS final_pdf_url TEXT;
ALTER TABLE signing_certificates ADD COLUMN IF NOT EXISTS generated_at TIMESTAMPTZ;
ALTER TABLE signing_certificates ADD COLUMN IF NOT EXISTS metadata JSONB;
ALTER TABLE signing_certificates ADD COLUMN IF NOT EXISTS signed_at TIMESTAMPTZ;
ALTER TABLE signing_certificates ADD COLUMN IF NOT EXISTS signer_email TEXT;
ALTER TABLE signing_certificates ADD COLUMN IF NOT EXISTS signing_package_id TEXT;
ALTER TABLE signing_certificates ADD COLUMN IF NOT EXISTS status TEXT DEFAULT 'issued';

-- ═══ SigningEvent → signing_events (9 missing) ═══
ALTER TABLE signing_events ADD COLUMN IF NOT EXISTS actor_email TEXT;
ALTER TABLE signing_events ADD COLUMN IF NOT EXISTS actor_name TEXT;
ALTER TABLE signing_events ADD COLUMN IF NOT EXISTS company_id TEXT DEFAULT 'rc-art';
ALTER TABLE signing_events ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ;
ALTER TABLE signing_events ADD COLUMN IF NOT EXISTS document_id TEXT;
ALTER TABLE signing_events ADD COLUMN IF NOT EXISTS document_type TEXT;
ALTER TABLE signing_events ADD COLUMN IF NOT EXISTS event_type TEXT;
ALTER TABLE signing_events ADD COLUMN IF NOT EXISTS metadata JSONB;
ALTER TABLE signing_events ADD COLUMN IF NOT EXISTS signing_package_id TEXT;

-- ═══ SigningPackage → signing_packages (44 missing) ═══
ALTER TABLE signing_packages ADD COLUMN IF NOT EXISTS active_participant_id TEXT;
ALTER TABLE signing_packages ADD COLUMN IF NOT EXISTS audit_summary JSONB;
ALTER TABLE signing_packages ADD COLUMN IF NOT EXISTS certificate_id TEXT;
ALTER TABLE signing_packages ADD COLUMN IF NOT EXISTS client_id TEXT;
ALTER TABLE signing_packages ADD COLUMN IF NOT EXISTS client_name TEXT;
ALTER TABLE signing_packages ADD COLUMN IF NOT EXISTS company_id TEXT DEFAULT 'rc-art';
ALTER TABLE signing_packages ADD COLUMN IF NOT EXISTS company_logo_url TEXT;
ALTER TABLE signing_packages ADD COLUMN IF NOT EXISTS document_fields JSONB;
ALTER TABLE signing_packages ADD COLUMN IF NOT EXISTS document_id TEXT;
ALTER TABLE signing_packages ADD COLUMN IF NOT EXISTS document_number TEXT;
ALTER TABLE signing_packages ADD COLUMN IF NOT EXISTS document_title TEXT;
ALTER TABLE signing_packages ADD COLUMN IF NOT EXISTS document_type TEXT;
ALTER TABLE signing_packages ADD COLUMN IF NOT EXISTS expired_at TIMESTAMPTZ;
ALTER TABLE signing_packages ADD COLUMN IF NOT EXISTS expires_at TIMESTAMPTZ;
ALTER TABLE signing_packages ADD COLUMN IF NOT EXISTS field_config JSONB;
ALTER TABLE signing_packages ADD COLUMN IF NOT EXISTS final_pdf_hash TEXT;
ALTER TABLE signing_packages ADD COLUMN IF NOT EXISTS final_pdf_url TEXT;
ALTER TABLE signing_packages ADD COLUMN IF NOT EXISTS hash_algorithm TEXT DEFAULT 'SHA-256';
ALTER TABLE signing_packages ADD COLUMN IF NOT EXISTS otp_delivery_channel TEXT;
ALTER TABLE signing_packages ADD COLUMN IF NOT EXISTS otp_expires_at TIMESTAMPTZ;
ALTER TABLE signing_packages ADD COLUMN IF NOT EXISTS otp_locked_until TEXT;
ALTER TABLE signing_packages ADD COLUMN IF NOT EXISTS otp_masked_destination TEXT;
ALTER TABLE signing_packages ADD COLUMN IF NOT EXISTS otp_required BOOLEAN DEFAULT false;
ALTER TABLE signing_packages ADD COLUMN IF NOT EXISTS otp_verified BOOLEAN DEFAULT false;
ALTER TABLE signing_packages ADD COLUMN IF NOT EXISTS package_number NUMERIC;
ALTER TABLE signing_packages ADD COLUMN IF NOT EXISTS page_count NUMERIC DEFAULT 0;
ALTER TABLE signing_packages ADD COLUMN IF NOT EXISTS participant_id TEXT;
ALTER TABLE signing_packages ADD COLUMN IF NOT EXISTS provider TEXT;
ALTER TABLE signing_packages ADD COLUMN IF NOT EXISTS sent_at TIMESTAMPTZ;
ALTER TABLE signing_packages ADD COLUMN IF NOT EXISTS signature_brand_logo_url TEXT;
ALTER TABLE signing_packages ADD COLUMN IF NOT EXISTS signer_email TEXT;
ALTER TABLE signing_packages ADD COLUMN IF NOT EXISTS signer_phone TEXT;
ALTER TABLE signing_packages ADD COLUMN IF NOT EXISTS signing_mode TEXT;
ALTER TABLE signing_packages ADD COLUMN IF NOT EXISTS signing_package_id TEXT;
ALTER TABLE signing_packages ADD COLUMN IF NOT EXISTS source_pdf_hash TEXT;
ALTER TABLE signing_packages ADD COLUMN IF NOT EXISTS source_pdf_name TEXT;
ALTER TABLE signing_packages ADD COLUMN IF NOT EXISTS source_pdf_url TEXT;
ALTER TABLE signing_packages ADD COLUMN IF NOT EXISTS status TEXT DEFAULT 'draft';
ALTER TABLE signing_packages ADD COLUMN IF NOT EXISTS token TEXT;
ALTER TABLE signing_packages ADD COLUMN IF NOT EXISTS token_created_at TIMESTAMPTZ;
ALTER TABLE signing_packages ADD COLUMN IF NOT EXISTS token_hash TEXT;
ALTER TABLE signing_packages ADD COLUMN IF NOT EXISTS token_last_four TEXT;
ALTER TABLE signing_packages ADD COLUMN IF NOT EXISTS token_revoked_at TIMESTAMPTZ;
ALTER TABLE signing_packages ADD COLUMN IF NOT EXISTS viewed_at TIMESTAMPTZ;

-- ═══ SigningParticipant → signing_participants (16 missing) ═══
ALTER TABLE signing_participants ADD COLUMN IF NOT EXISTS company_id TEXT DEFAULT 'rc-art';
ALTER TABLE signing_participants ADD COLUMN IF NOT EXISTS email TEXT;
ALTER TABLE signing_participants ADD COLUMN IF NOT EXISTS metadata JSONB;
ALTER TABLE signing_participants ADD COLUMN IF NOT EXISTS name TEXT;
ALTER TABLE signing_participants ADD COLUMN IF NOT EXISTS reminder_count NUMERIC DEFAULT 0;
ALTER TABLE signing_participants ADD COLUMN IF NOT EXISTS reminder_last_sent_at TIMESTAMPTZ;
ALTER TABLE signing_participants ADD COLUMN IF NOT EXISTS role TEXT DEFAULT 'signer';
ALTER TABLE signing_participants ADD COLUMN IF NOT EXISTS sent_at TIMESTAMPTZ;
ALTER TABLE signing_participants ADD COLUMN IF NOT EXISTS signed_at TIMESTAMPTZ;
ALTER TABLE signing_participants ADD COLUMN IF NOT EXISTS signing_order NUMERIC DEFAULT 1;
ALTER TABLE signing_participants ADD COLUMN IF NOT EXISTS signing_package_id TEXT;
ALTER TABLE signing_participants ADD COLUMN IF NOT EXISTS token TEXT;
ALTER TABLE signing_participants ADD COLUMN IF NOT EXISTS token_created_at TIMESTAMPTZ;
ALTER TABLE signing_participants ADD COLUMN IF NOT EXISTS token_hash TEXT;
ALTER TABLE signing_participants ADD COLUMN IF NOT EXISTS token_last_four TEXT;
ALTER TABLE signing_participants ADD COLUMN IF NOT EXISTS token_revoked_at TIMESTAMPTZ;

-- ═══ TimeEntry → time_entries (16 missing) ═══
ALTER TABLE time_entries ADD COLUMN IF NOT EXISTS client_name TEXT;
ALTER TABLE time_entries ADD COLUMN IF NOT EXISTS date DATE;
ALTER TABLE time_entries ADD COLUMN IF NOT EXISTS duration_seconds NUMERIC DEFAULT 0;
ALTER TABLE time_entries ADD COLUMN IF NOT EXISTS end_lat NUMERIC;
ALTER TABLE time_entries ADD COLUMN IF NOT EXISTS end_lng NUMERIC;
ALTER TABLE time_entries ADD COLUMN IF NOT EXISTS end_time TEXT;
ALTER TABLE time_entries ADD COLUMN IF NOT EXISTS gps_track JSONB;
ALTER TABLE time_entries ADD COLUMN IF NOT EXISTS miles_traveled NUMERIC DEFAULT 0;
ALTER TABLE time_entries ADD COLUMN IF NOT EXISTS note TEXT;
ALTER TABLE time_entries ADD COLUMN IF NOT EXISTS project TEXT;
ALTER TABLE time_entries ADD COLUMN IF NOT EXISTS service TEXT;
ALTER TABLE time_entries ADD COLUMN IF NOT EXISTS start_lat NUMERIC;
ALTER TABLE time_entries ADD COLUMN IF NOT EXISTS start_lng NUMERIC;
ALTER TABLE time_entries ADD COLUMN IF NOT EXISTS start_time TEXT;
ALTER TABLE time_entries ADD COLUMN IF NOT EXISTS status TEXT DEFAULT 'running';
ALTER TABLE time_entries ADD COLUMN IF NOT EXISTS team_member TEXT;

-- ═══ TimeTrackingLog → time_tracking_logs (18 missing) ═══
ALTER TABLE time_tracking_logs ADD COLUMN IF NOT EXISTS appointment_id TEXT;
ALTER TABLE time_tracking_logs ADD COLUMN IF NOT EXISTS customer_id TEXT;
ALTER TABLE time_tracking_logs ADD COLUMN IF NOT EXISTS customer_name TEXT;
ALTER TABLE time_tracking_logs ADD COLUMN IF NOT EXISTS duration_minutes NUMERIC DEFAULT 0;
ALTER TABLE time_tracking_logs ADD COLUMN IF NOT EXISTS end_lat NUMERIC;
ALTER TABLE time_tracking_logs ADD COLUMN IF NOT EXISTS end_lng NUMERIC;
ALTER TABLE time_tracking_logs ADD COLUMN IF NOT EXISTS end_location TEXT;
ALTER TABLE time_tracking_logs ADD COLUMN IF NOT EXISTS end_time TEXT;
ALTER TABLE time_tracking_logs ADD COLUMN IF NOT EXISTS miles_traveled NUMERIC DEFAULT 0;
ALTER TABLE time_tracking_logs ADD COLUMN IF NOT EXISTS notes TEXT;
ALTER TABLE time_tracking_logs ADD COLUMN IF NOT EXISTS start_lat NUMERIC;
ALTER TABLE time_tracking_logs ADD COLUMN IF NOT EXISTS start_lng NUMERIC;
ALTER TABLE time_tracking_logs ADD COLUMN IF NOT EXISTS start_location TEXT;
ALTER TABLE time_tracking_logs ADD COLUMN IF NOT EXISTS start_time TEXT;
ALTER TABLE time_tracking_logs ADD COLUMN IF NOT EXISTS status TEXT DEFAULT 'active';
ALTER TABLE time_tracking_logs ADD COLUMN IF NOT EXISTS tracking_type TEXT DEFAULT 'travel';
ALTER TABLE time_tracking_logs ADD COLUMN IF NOT EXISTS worker_id TEXT;
ALTER TABLE time_tracking_logs ADD COLUMN IF NOT EXISTS worker_name TEXT;

-- ═══ WorkerDocument → worker_documents (6 missing) ═══
ALTER TABLE worker_documents ADD COLUMN IF NOT EXISTS doc_type TEXT DEFAULT 'other';
ALTER TABLE worker_documents ADD COLUMN IF NOT EXISTS expiry_date DATE;
ALTER TABLE worker_documents ADD COLUMN IF NOT EXISTS file_url TEXT;
ALTER TABLE worker_documents ADD COLUMN IF NOT EXISTS name TEXT;
ALTER TABLE worker_documents ADD COLUMN IF NOT EXISTS notes TEXT;
ALTER TABLE worker_documents ADD COLUMN IF NOT EXISTS worker_name TEXT;

-- ═══ WorkerNote → worker_notes (3 missing) ═══
ALTER TABLE worker_notes ADD COLUMN IF NOT EXISTS content TEXT;
ALTER TABLE worker_notes ADD COLUMN IF NOT EXISTS created_by TEXT;
ALTER TABLE worker_notes ADD COLUMN IF NOT EXISTS worker_name TEXT;

-- ═══ WorkOrderDailyReport → work_order_daily_reports (13 missing) ═══
ALTER TABLE work_order_daily_reports ADD COLUMN IF NOT EXISTS arrival_time TEXT;
ALTER TABLE work_order_daily_reports ADD COLUMN IF NOT EXISTS departure_time TEXT;
ALTER TABLE work_order_daily_reports ADD COLUMN IF NOT EXISTS issues_found TEXT;
ALTER TABLE work_order_daily_reports ADD COLUMN IF NOT EXISTS labor_hours NUMERIC DEFAULT 0;
ALTER TABLE work_order_daily_reports ADD COLUMN IF NOT EXISTS next_steps TEXT;
ALTER TABLE work_order_daily_reports ADD COLUMN IF NOT EXISTS summary_of_work TEXT;
ALTER TABLE work_order_daily_reports ADD COLUMN IF NOT EXISTS tasks_completed TEXT;
ALTER TABLE work_order_daily_reports ADD COLUMN IF NOT EXISTS tasks_pending TEXT;
ALTER TABLE work_order_daily_reports ADD COLUMN IF NOT EXISTS travel_hours NUMERIC DEFAULT 0;
ALTER TABLE work_order_daily_reports ADD COLUMN IF NOT EXISTS worker_id TEXT;
ALTER TABLE work_order_daily_reports ADD COLUMN IF NOT EXISTS worker_name TEXT;
ALTER TABLE work_order_daily_reports ADD COLUMN IF NOT EXISTS work_date DATE;
ALTER TABLE work_order_daily_reports ADD COLUMN IF NOT EXISTS work_order_number NUMERIC;

-- ═══ WorkOrderExpense → work_order_expenses (10 missing) ═══
ALTER TABLE work_order_expenses ADD COLUMN IF NOT EXISTS cash_advance_amount NUMERIC DEFAULT 0;
ALTER TABLE work_order_expenses ADD COLUMN IF NOT EXISTS description TEXT;
ALTER TABLE work_order_expenses ADD COLUMN IF NOT EXISTS expense_type TEXT DEFAULT 'materials';
ALTER TABLE work_order_expenses ADD COLUMN IF NOT EXISTS notes TEXT;
ALTER TABLE work_order_expenses ADD COLUMN IF NOT EXISTS payment_method TEXT DEFAULT 'cash';
ALTER TABLE work_order_expenses ADD COLUMN IF NOT EXISTS reimbursable BOOLEAN DEFAULT false;
ALTER TABLE work_order_expenses ADD COLUMN IF NOT EXISTS vendor TEXT;
ALTER TABLE work_order_expenses ADD COLUMN IF NOT EXISTS worker_id TEXT;
ALTER TABLE work_order_expenses ADD COLUMN IF NOT EXISTS worker_name TEXT;
ALTER TABLE work_order_expenses ADD COLUMN IF NOT EXISTS work_order_number NUMERIC;

-- ═══ WorkOrderHistory → work_order_histories (6 missing) ═══
ALTER TABLE work_order_histories ADD COLUMN IF NOT EXISTS changed_by TEXT;
ALTER TABLE work_order_histories ADD COLUMN IF NOT EXISTS change_note TEXT;
ALTER TABLE work_order_histories ADD COLUMN IF NOT EXISTS field_changed TEXT;
ALTER TABLE work_order_histories ADD COLUMN IF NOT EXISTS new_value TEXT;
ALTER TABLE work_order_histories ADD COLUMN IF NOT EXISTS old_value TEXT;
ALTER TABLE work_order_histories ADD COLUMN IF NOT EXISTS work_order_number NUMERIC;

-- ═══ WorkOrderReceipt → work_order_receipts (8 missing) ═══
ALTER TABLE work_order_receipts ADD COLUMN IF NOT EXISTS amount NUMERIC DEFAULT 0;
ALTER TABLE work_order_receipts ADD COLUMN IF NOT EXISTS expense_id TEXT;
ALTER TABLE work_order_receipts ADD COLUMN IF NOT EXISTS file_name TEXT;
ALTER TABLE work_order_receipts ADD COLUMN IF NOT EXISTS file_url TEXT;
ALTER TABLE work_order_receipts ADD COLUMN IF NOT EXISTS notes TEXT;
ALTER TABLE work_order_receipts ADD COLUMN IF NOT EXISTS receipt_date DATE;
ALTER TABLE work_order_receipts ADD COLUMN IF NOT EXISTS uploaded_by TEXT;
ALTER TABLE work_order_receipts ADD COLUMN IF NOT EXISTS vendor TEXT;

-- ═══ WorkOrderTimeEntry → work_order_time_entries (8 missing) ═══
ALTER TABLE work_order_time_entries ADD COLUMN IF NOT EXISTS company_id TEXT DEFAULT 'rc-art';
ALTER TABLE work_order_time_entries ADD COLUMN IF NOT EXISTS duration_hours NUMERIC;
ALTER TABLE work_order_time_entries ADD COLUMN IF NOT EXISTS end_time TEXT;
ALTER TABLE work_order_time_entries ADD COLUMN IF NOT EXISTS notes TEXT;
ALTER TABLE work_order_time_entries ADD COLUMN IF NOT EXISTS start_time TEXT;
ALTER TABLE work_order_time_entries ADD COLUMN IF NOT EXISTS worker_id TEXT;
ALTER TABLE work_order_time_entries ADD COLUMN IF NOT EXISTS worker_name TEXT;
ALTER TABLE work_order_time_entries ADD COLUMN IF NOT EXISTS work_date DATE;

